### PR TITLE
Update to JRE and set alpine version

### PR DESCRIPTION
**Pull request by devx**
I used  Vladimir Krivosheev as the bases for the template for the JRE images, with a minor change to leave ca-certificates .  In addition to that I have also  set alpine to 3.2.

### CODE REVIEW

**Comment by devx** [comment]
- The main reason for setting alpine to 3.3 is to be explicit as alpine can change at anytime and might cause some issues. 
- The Glibc bin is used to was used to update the share library cache in /etc/ld.so.cache.  Which is used to map the share library name to a location. 
- I did not thing adding upgrade was needed as the base image is 5megs and it doesn’t really have any packages.  But we can always add the so if you prefer it I can just update the pr with that.
- Lastly not sure if you were asking why this JRE approach is better.  If so the main reason is that this cuts the JRE size by ~60 megs.

**Comment by anapsix** [comment]
> The main reason for setting alpine to 3.3 is to be explicit as alpine can change at anytime and might cause some issues.

Good point, NodeJS is broken in alpine:3.3, for example.

---

> The Glibc bin is used to was used to update the share library cache in /etc/ld.so.cache. Which is used to map the share library name to a location.

makes sense

---

> I did not think adding upgrade was needed as the base image is 5megs and it doesn’t really have any packages. But we can always add the so if you prefer it I can just update the pr with that.

It won't add to image size much (if anything), but it won't hurt..

---

> Lastly not sure if you were asking why this JRE approach is better. If so the main reason is that this cuts the JRE size by ~60 megs.

Indeed, another 60MB saved is great!

---

As soon as circle-artifacts.com stabilizes and I have some time, I'll build these locally and test our few apps, just in case.
- since there is no difference between `Dockerfile.jdk.tpl` and `Dockerfile.jre.tpl`, why have both?
- could we keep the location of JRE/JDK consistently in /opt?
- don't we want to install "glibc-bin" in all images (JRE7/JDK7/JRE8/JDK8) for the same purpose?

**Comment by anapsix** [comment]
yeah.... it's mostly a copy of https://github.com/develar/docker-java/blob/master/Dockerfile
let's clean it up..
Don't get me wrong, I like what Vladimir did slashing image size by another ~60MB..

**Comment by anapsix** [comment]
merged manually with some fixes, thanks

**Pull request closed without merging**
