### PR TITLE
[version] Updated to support java 1.8.0_111-b14 and dcevm 8u112

### PR DESCRIPTION
**Pull request by albundy83**

### CODE REVIEW

**Review by anapsix — CHANGES_REQUESTED** [review]
well, I was hoping you'd submit the update to include new dcevm version, leaving "current" at 8-112-15

**Comment by albundy83** [comment]
Sorry, I did not understand what you mean ....

**Comment by anapsix** [comment]
just to make sure it's clear I'll rephrase it..

this PR includes a Java version update as well as newer DCEVM version.
Since your Java version is older then what's on master, after I've merged #25 PSU with [8u112](http://www.oracle.com/technetwork/java/javase/8u112-relnotes-3124973.html) (even though yours is bringing latest CPU, master is on latest PSU), I'd love to include your DCEVM update

**Comment by albundy83** [comment]
Ok, this time it's more clear :-) https://github.com/anapsix/docker-alpine-java/pull/31

**Comment by anapsix** [comment]
gonna close this one in favor of #31

**Pull request closed without merging**
