### PR TITLE
Update for JDK 8u112b15

### PR DESCRIPTION
**Pull request by praseodym**

### CODE REVIEW

**Comment by anapsix** [comment]
Did you had a chance to take a look at at Travis-CI "gunzip: invalid magic"
https://travis-ci.org/anapsix/docker-alpine-java/builds/171843376

**Comment by praseodym** [comment]
Whoops, apparently the Linux build has b15 (macOS is b16). I also added `set -ex` for easier debugging.

**Comment by timothyklim** [comment]
Is there any news?

**Review by anapsix — APPROVED** [review]
looking good

**Comment by anapsix** [comment]
thanks @praseodym !!

**Pull request merged**
