### PR TITLE
Generalize Java environment variables and setup

### PR DESCRIPTION
**Pull request by zeridon**
In order for easier forking, rearangement of installations all paths must be as parametric
as possible.

This pach achieves this by:
- Introduce new variable `JAVA_BASE_DIR` which points to the base where all JRE/JDK will be installed
- Ammend `JAVA_HOME` and `PATH` to include `JAVA_BASE_DIR`
- convert all `mkdir` to `mkdir -p` to allow for deeper structures
- Use `JAVA_BASE_DIR` and `JAVA_HOME` everywhere possible
- Use `JAVA_HOME` in cleanup step

### CODE REVIEW

**Review by anapsix — COMMENTED** [review]
He-he, yep

**Comment by zeridon** [comment]
Any objections on merging this. Personally i believe this is much more usable (especially in the case of custom builds).

**Comment by anapsix** [comment]
Imo, it's marginally better.
Not sure how it helps with custom builds, but I don't mind it.
I do need to test it first, since you've clearly made and submitted changes
without trying it out first.

**Comment by anapsix** [comment]
with bunch of more recent changes, this need to be rebased...
sorry I haven't been paying attention to this repo for awhile..
I'll revisit your suggestion at some point

**Pull request closed without merging**
